**Data Analytics End to End Project: Customer Behaviour Analysis**

Importing Libraries to perform analysis

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Loading the Dataset

In [ ]:
cust_data=pd.read_csv('/content/customer_shopping_behavior.csv')
cust_data.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [ ]:
#Description of dataset
cust_data.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [ ]:
#Rows and columns of data
cust_data.shape

(3900, 18)

In [ ]:
#Extracting the Null Values
cust_data.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
#We are replacing the null values of Reviews Ratings columns with Imputing Median Values based on Category column
cust_data['Review Rating']=cust_data.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [ ]:
cust_data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
#Converting the columns into Snake Casing for better analysis in the further process.
cust_data.columns=cust_data.columns.str.lower()
cust_data.columns=cust_data.columns.str.replace(' ','_')
cust_data.columns
cust_data.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

**Feature Engineering**

In [ ]:
#Create a columns age group based on Ages
labels=['Young Adults','Adult','Middle-Aged','Senior Citizens']
cust_data['age_group']=pd.qcut(cust_data['age'],4,labels=labels)

In [ ]:
cust_data[['age','age_group']].head(20)

    age        age_group
0    55      Middle-Aged
1    19     Young Adults
2    50      Middle-Aged
3    21     Young Adults
4    45      Middle-Aged
5    46      Middle-Aged
6    63  Senior Citizens
7    27     Young Adults
8    26     Young Adults
9    57      Middle-Aged
10   53      Middle-Aged
11   30     Young Adults
12   61  Senior Citizens
13   65  Senior Citizens
14   64  Senior Citizens
15   64  Senior Citizens
16   25     Young Adults
17   53      Middle-Aged
18   52      Middle-Aged
19   66  Senior Citizens

In [ ]:
#Create a column purchase_frequency_days
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}

cust_data['purchase_frequency_days']=cust_data['frequency_of_purchases'].map(frequency_mapping)

In [ ]:
cust_data[['frequency_of_purchases','purchase_frequency_days']].head(20)

   frequency_of_purchases  purchase_frequency_days
0             Fortnightly                       14
1             Fortnightly                       14
2                  Weekly                        7
3                  Weekly                        7
4                Annually                      365
5                  Weekly                        7
6               Quarterly                       90
7                  Weekly                        7
8                Annually                      365
9               Quarterly                       90
10              Bi-Weekly                       14
11            Fortnightly                       14
12            Fortnightly                       14
13                 Weekly                        7
14                 Weekly                        7
15                Monthly                       30
16              Bi-Weekly                       14
17              Quarterly                       90
18                 Weekly                        7
19              Bi-Weekly                       14

In [ ]:
#Performing operation on Discount Applied and promo Code Used
cust_data[['discount_applied','promo_code_used']].head(20)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes
11              Yes             Yes
12              Yes             Yes
13              Yes             Yes
14              Yes             Yes
15              Yes             Yes
16              Yes             Yes
17              Yes             Yes
18              Yes             Yes
19              Yes             Yes

In [ ]:
(cust_data['discount_applied']==cust_data['promo_code_used']).all()

np.True_

In [ ]:
cust_data=cust_data.drop('promo_code_used',axis=1)
cust_data

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adults,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adults,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-Aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-Aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-Aged,90

Connecting the Google Colab with MYSQL Database

```markdown
### Step 1: Install and Start MySQL Server on Colab VM
Since Colab runs on a temporary Linux environment without MySQL, we must install, configure, and start it before connecting.
```

In [ ]:
# Install MySQL Server
!apt-get update > /dev/null
!apt-get install -y mysql-server > /dev/null

# Start the MySQL service
!service mysql start

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
 * Starting MySQL database server mysqld        su: warning: cannot change directory to /nonexistent: No such file or directory
[ OK ]

```markdown
### Step 2: Configure MySQL User & Create Database
We will set the root password and create the required database `Analytics_db` inside our new MySQL instance.
```

In [ ]:
# Set password for 'root'@'localhost' and create the 'Analytics_db' database
!mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Ashraf@9900';"
!mysql -u root -p'Ashraf@9900' -e "CREATE DATABASE IF NOT EXISTS Analytics_db;"

mysql: [Warning] Using a password on the command line interface can be insecure.

```markdown
### Step 3: Load the Customer Behaviour Data into MySQL
Now that the database server is running locally on 127.0.0.1, we can write the DataFrame to the engine.
```

In [ ]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = "Ashraf@9900"
host = "127.0.0.1"
port = "3306"
database = "Analytics_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{quote_plus(password)}@{host}:{port}/{database}"
)

table_name = "customer_behaviour"
cust_data.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer_behaviour' in database 'Analytics_db'.

```markdown
### Step 4: Verify the Database Load
We can read the table back from the MySQL database into a new pandas DataFrame to verify that all rows were stored correctly.
```

In [ ]:
# Query the first 5 rows from the table in the MySQL database
loaded_data = pd.read_sql("SELECT * FROM customer_behaviour LIMIT 5;", con=engine)

# Display the loaded data to confirm
display(loaded_data)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adults,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adults,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365

In [ ]:
# Export the database to a .sql dump file
!mysqldump -u root -p'Ashraf@9900' --databases Analytics_db > analytics_db_backup.sql
print("Database successfully exported! You can now download 'analytics_db_backup.sql' from the file explorer on the left.")

mysqldump: [Warning] Using a password on the command line interface can be insecure.
Database successfully exported! You can now download 'analytics_db_backup.sql' from the file explorer on the left.